version: '3'

networks:
    laravel:
        driver: bridge

services:
    nginx2:
        image: nginx:alpine
        container_name: nginx2
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes:
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php2
            - mysql2
        networks:
            - laravel

    mysql2:
        platform: linux/amd64
        image: mysql
        container_name: mysql2
        restart: unless-stopped
        tty: true
        ports:
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel_docker
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php2
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes:
            - ./src:/var/www/app
        ports:
            - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        networks:
            - laravel
